# 自定义配置
apigrid-config:
  default-password: ${DEFAULT_PASSWORD:123456}

# 数据源配置
spring:
  main:
    #当遇到相同名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true

  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  100MB

  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${MYSQL_HOST:192.168.4.234}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:apigrid}?characterEncoding=utf8&useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:S2AbuXsMUDHCzMQM}

  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST:192.168.4.234}
    # 端口，默认为6379
    port: ${REDIS_PORT:6379}
    # 数据库索引
    database: ${REDIS_DB:7}
    # 密码
    password: ${REDIS_PASSWORD:DPU8tGUCYSlIJ1gG}
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  # mongodb
  data:
    mongodb:
      uri: mongodb://admin:S2AbuXsMUDHCzMQM@192.168.4.234:27017/apigrid

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认720分钟）
  expireTime: 720

# auth-token
auth:
  # hbms:l^gDaQm1sjJ5vCz9
  basicToken: "aGJtczpsXmdEYVFtMXNqSjV2Q3o5"
  urlPatterns: /cgi-api/*

# 文件上传
minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.4.234:9000}
  accessKey: ${MINIO_ACCESS_KEY:p5nUlIGix6X2PFxL}
  secretKey: ${MINIO_SECRET_KEY:NjFQrtEys3KCJxkRB9geYnh9UlgWHt96}
  bucketName: ${OSS_BUCKET_NAME:assets}