#端口安排
# web-server      9000
# backend-server  9001
# redis           6379
# mysql           3306
# mongodb         27017

# 自定义配置
apigrid-config:
  default-password: ${DEFAULT_PASSWORD:666666}

# 数据源配置
spring:
  datasource:
    #    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${MYSQL_HOST:192.168.4.198}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:apigrid}?characterEncoding=utf8&useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:apigrid!com}

  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST:192.168.4.198}
    # 端口，默认为6379
    port: ${REDIS_PORT:6379}
    # 数据库索引
    database: ${REDIS_DB:0}
    # 密码
    password: ${REDIS_PASSWORD:apigrid!com}
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  # mongodb
  data:
    mongodb:
      #      uri: mongodb://root:apigrid@192.168.4.198:27017/apigrid
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:apigrid!com}
      host: ${MONGO_HOST:192.168.4.198}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:apigrid}

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认720分钟）
  expireTime: 720

# auth-token
auth:
  # root:apigrid
  basicToken: "cm9vdDphcGlncmlk"
  urlPatterns: /cgi-api/*

# 文件上传
minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.4.198:9000}
  accessKey: ${MINIO_ACCESS_KEY:root}
  secretKey: ${MINIO_SECRET_KEY:apigrid!com}
  bucketName: ${OSS_BUCKET_NAME:assets}