#端口安排
# web-server      9000
# backend-server  9001
# redis           6379
# mysql           3306
# mongodb         27017

server:
  port: 9001

spring:
  profiles:
    active: dev
  main:
    #当遇到相同名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 100MB

# 日志配置
logging:
  level:
    org.springframework: info
  config: classpath:logback-spring.xml
  file:
    path: ./logs
