version: "3.9"

services:

  mongo-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_MONGODB_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    container_name: mongo-server
    restart: always
    env_file:
      - "${ENV_FILE:-.env}"
    ports:
      - "27017:27017"
    environment:
      - TZ=${TIMEZONE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-apigrid}
    networks:
      - apigrid
    volumes:
      - ~/docker/mongo-server:/data/mongodb
    command: --wiredTigerCacheSizeGB 4 --auth # 限制内存大小, 需要认证

  mongo-express:
    image: ${IMAGE_REGISTRY}/${IMAGE_MONGO_EXPRESS_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    container_name: mongo-express
    restart: always
    ports:
      - "9021:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD:-apigrid}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST:-192.168.4.198}

networks:
  apigrid:
    name: apigrid_default
    driver: bridge